import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"

import Providers from "@/components/Providers"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <Header />
            <div>{children}</div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
